### ISSUE TITLE
Any way to use QuickChick without opam?

### ISSUE THREAD

**Issue by catalin-hritcu** [QuickChick/QuickChick#103]
Call me old, but I like to compile Coq directly, not via opam. Now, is there any way I can use QuickChick with a version of Coq that is compiled from source with the `-local` configure flag?

I'm currently trying this for Coq 8.7.1, but getting the following error:
```
ocamlbuild -use-ocamlfind -pkg coq.lib -cflags -rectypes -tag thread quickChickTool/quickChickTool.byte
+ ocamlfind ocamldep -package coq.lib -modules quickChickTool/quickChickTool.ml > quickChickTool/quickChickTool.ml.depends
ocamlfind: Package `coq.lib' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
make: *** [Makefile:52: quickChickTool.byte] Error 10
```
I guess it's related to not finding the `META.coq` file or something like that.

**Comment by liyishuai** [comment]
I think it's OK to use batteries, but my current solution to #102 depends on [coq.extractionlib](https://github.com/coq/coq/pull/8252):
https://github.com/QuickChick/QuickChick/blob/e07e9ac1fd409578a792ae05b557f9faf2b44f0c/quickChickTool/quickChickTool.ml#L366
Is there a way to utilize the Coq packages installed locally?

**Comment by catalin-hritcu** [comment]
Is opam still the only supported way to build QuickChick?

**Comment by Lysxia** [comment]
I'm afraid that's still the case. I'll try to pull the plug on that coqlib dependency in the next few days.
