### ISSUE TITLE
`quickChickTool` parses in `.git` directory

### ISSUE THREAD

**Issue by liyishuai** [QuickChick/QuickChick#105]
> Parse error when reading file: ./.git/objects/3a/b37c085b31341f76d2c4404b8cf2492d32d6cc
Fatal error: exception Failure("Error in line 1, position 135")

I can shadow this "feature" with `-exclude ".git"`, but shall we have `quickChickTool` always ignore `.git*` instead?

**Comment by liyishuai** [comment]
`quickChickTool` parses into files ending with `c`. We should change the filter into `.c`.

**Comment by Lysxia** [comment]
I think it would be better to fix `-include`.

**Comment by liyishuai** [comment]
Does `-include` take `_CoqProject` as argument? If yes, then are we including `.c` files in `_CoqProject`?

**Comment by Lysxia** [comment]
It should probably not be a `_CoqProject`, that has too many restrictions as you mention. (and the `coq.lib` dependency to parse them was a mess). Either put it in a different file specially for this purpose, or pass the files to include via the command line (`-include` takes the rest of the files like `-exclude` currently does, of course they would be mutually exclusive options in that case, but my point is to deprecate `-exclude` anyhow).

**Comment by liyishuai** [comment]
For now, netiher `-include` nor `-exclude` supports subdirectory. I've applied a partial fix that only compares the basename. I'm also in favor of deprecating `-exclude`, and redesigning `-include`.
