### ISSUE TITLE
Unprovable facts about checker combinators

### ISSUE THREAD

**Issue by zoep** [QuickChick/QuickChick#12]
There are some proofs that are commented out in file EndToEnd.v. Those proofs do not seem provable in the new setting, although they were provable in the previous coarse approach. The main problem is that the spec of bind is weaker than we initially thought.  Some of the unprovable statements are key facts like the specs of forAll and forAllShrink combinators.

**Comment by zoep** [comment]
All statements become provable when we are explicit about sizes. That makes sense and it seems that in the general case we can get rid of size only at the highest level (i.e. the final statement we prove about a generator/checker). Should we remove theorems and definitions that abstract over size (semGen and theorems that use it) and keep only semSize?

**Comment by catalin-hritcu** [comment]
I agree with what you say, but I don't see why we would remove semGen. Don't we still use it at the top level?

**Comment by zoep** [comment]
When we want to prove something about a checker then we don't need it because the semChecker uses semSize. If we want to prove something about a generator only then we could use semGen at the top level. In any case it doesn't hurt to keep it.
