### ISSUE TITLE
On CoqIDE, QuickChick prints to terminal instead of the message window.

### ISSUE THREAD

**Issue by Lysxia** [QuickChick/QuickChick#120]
Steps to reproduce: open coqIDE, run `Require Import QuickChick.QuickChick. QuickChick true.`

https://sympa.inria.fr/sympa/arc/coq-club/2018-10/msg00064.html

**Comment by Chobbes** [comment]
This was also brought up in this issue:

https://github.com/QuickChick/QuickChick/issues/96
