### ISSUE TITLE
Coverage of FuzzChick

### ISSUE THREAD

**Issue by liyishuai** [QuickChick/QuickChick#126]
FuzzChick cannot crash this:
```coq
From QuickChick Require Import QuickChick.                                       
FuzzChick (fun n => n < 8?).
```
but if I substitute `8` with `7`, it crashes immediately.
Is this result expected?

**Comment by lemonidas** [comment]
Probably because the arbitrary instance for nat is choosing up to the size parameter and the default size parameter is 7? 
As a side note, why are we opening a github issue for every single tiny thing? Especially about ongoing threads like fuzzchick that are nowhere near ready to be used by other people...

**Comment by liyishuai** [comment]
Avoiding `nat` makes it more interesting:
```coq
Inductive naat := OO | SS : naat -> naat.
Fixpoint to_nat (n : naat) : nat :=
  match n with
  | OO => O
  | SS n' => S (to_nat n')
  end.
Derive Arbitrary for naat.
Derive Show for naat.
FuzzChick (fun n => (to_nat n) < 8?).
```
It has covered 9 paths without crashing.

**Comment by lemonidas** [comment]
This literally changes nothing. The default Arbitrary generator will generate naat of size up to the default depth. That is 7 SS constructors. Why is this more interesting?

**Comment by liyishuai** [comment]
With `nat`, the number of paths is 1 and non increasing.
If there are at most 7 `SS` constructors, how come 9 execution paths?

**Comment by lemonidas** [comment]
Default nat generator: choose (0, size).
Derived Arbitrary Generator for naat: up to size SS constructors.
Functionally, they are the same. Execution path wise, the instrumentation probably treats the recursion in the generation as different paths. I still fail to see the point of this issue.
