### ISSUE TITLE
Error in Coq's CI

### ISSUE THREAD

**Issue by ejgallego** [QuickChick/QuickChick#129]
Hi folks, we got this in Coq's CI:
```
COQC src/Test.v
File "./src/Test.v", line 362, characters 2-31:
Error:
In environment
tests : list Test
The term "unsafe_run (testRunner tests)" has type 
"io_unit" while it is expected to have type "unit".
```
Is that an upstream problem?

**Comment by Lysxia** [comment]
That's caused by a breaking change from the master branch of coq-simple-io.

**Comment by Lysxia** [comment]
I forgot coq-simple-io is tracked by Coq CI. Is this failure only on QuickChick's master branch?

**Comment by ejgallego** [comment]
It is indeed in the `master` branch tested on Coq's CI.

**Comment by Lysxia** [comment]
OK I can fix this. For future reference, are there standard practices to better manage this kind of issue? As the developer of coq-simple-io I can work on another branch so not every little commit impacts Coq CI, but when I make a new release, should I just wait for Coq CI to complain or are there more active steps I can take?

**Comment by ejgallego** [comment]
Thanks for taking care of this issue @Lysxia !

Indeed we should improve this; how do you do w.r.t. to Quickchick's own CI?

**Comment by ejgallego** [comment]
I mean, what version of `coq-simple-io` do you test?

**Comment by Lysxia** [comment]
We're testing coq-simple-io `0.2` on both QuickChick `master` and `v8.8`. In fact, now that you mention it, I'm wondering how to apply my fix while keeping our CI happy. Perhaps QuickChick `master` should track coq-simple-io `master`. @liyishuai any ideas?

**Comment by ejgallego** [comment]
Maybe a better solution is to switch Coq to `coq-simple-io 0.2`; we test that package only as a dependency of Quickchick; the only downside would be that once you up the dependency here we would have to do that in Coq.

We have plan to avoid this problem but it will take time.

What `iris` people do is they have a makefile that knows what to install. That's another solution, tho we wil offer that natively in Coq soon I hope.

**Comment by liyishuai** [comment]
I agree that `coq-quickchick.dev` should use master branch of coq-simple-io. Let's release `coq-simple-io.dev` on extra-dev.

**Comment by ejgallego** [comment]
Ok, sounds good then, we will do no change on Coq's CI then; thanks @liyishuai @Lysxia !
