### ISSUE TITLE
Update/complete case studies

### ISSUE THREAD

**Issue by zoep** [QuickChick/QuickChick#13]
Update the case studies in order to use the new "axiom-free" setting. Files/folders that need to be updated:

Tests.v --> Completed
RedBlack/  --> Completed. (No sacrifice on the strength of the statements we prove)
ifc-basic/ (not finished)

**Comment by catalin-hritcu** [comment]
As discussed in the last call, it's still unclear whether we want to put effort in doing ifc-basic properly before we do IFC. The more valuable target is clearly IFC.

**Comment by catalin-hritcu** [comment]
So for now how about we make ifc-basic compile as is, close this issue, and track potential progress on proving things about ifc-basic in Issue #1

**Comment by zoep** [comment]
Sure, I can make both IFC developments compile with the current version of the framework.
