### ISSUE TITLE
Unbound value and unbound module errors

### ISSUE THREAD

**Issue by Tuplanolla** [QuickChick/QuickChick#137]
See coq/coq#9365.

#### Notes

I reported this bug to the Coq project
with a reference in the QuickChick project,
because I do not know whether this bug is caused by one or the other.

**Comment by liyishuai** [comment]
I can replicate the results in both 8.8 and master. Investigating.

**Comment by wilbowma** [comment]
I think I've run in to this problem. Seems to be related to using `Module`. Here are two test files, one of which works fine, one of which fails.
https://gist.github.com/wilbowma/243f6d4e6da048443f74caee20eec226

Versions:
```
> ~/.opam/4.07.1/bin/coqc --version
The Coq Proof Assistant, version 8.9.1 (September 2019)
compiled on Sep 3 2019 17:30:30 with OCaml 4.07.1

> opam list
# Packages matching: installed
# Name                 # Installed # Synopsis
base-bigarray          base
base-threads           base
base-unix              base
camlp5                 7.10        Preprocessor-pretty-printer of OCaml
conf-m4                1           Virtual package relying on m4
coq                    8.9.1       Formal proof management system
coq-ext-lib            0.10.2      A basic library of basic Coq datatypes, definitions, theorems, and
coq-mathcomp-ssreflect 1.9.0       Small Scale Reflection
coq-quickchick         1.1.0       Randomized Property-Based Testing Plugin for Coq
coq-simple-io          1.0.0       IO monad for Coq
num                    1.2         The legacy Num library for arbitrary-precision integer and rational arithmetic
ocaml                  4.07.1      The OCaml compiler (virtual package)
ocaml-base-compiler    4.07.1      Official release 4.07.1
ocaml-config           1           OCaml Switch Configuration
ocamlbuild             0.14.0      OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
ocamlfind              1.8.1       A library manager for OCaml
```

**Comment by liyishuai** [comment]
@Lysxia any insights? or should we handle this in QC2?

**Comment by Lysxia** [comment]
This seems to be an extraction issue, not specific to QuickChick.

The following snippet, with a definition at the toplevel, then a `Recursive Extraction` command inside a module, extracts to literally nothing (tested on Coq 8.9):

```
Require Extraction.

Definition f := 0.
Module M.
  Recursive Extraction f.
```

**Comment by Lysxia** [comment]
Moved to coq/coq#10739

As of now, `Extraction` and `QuickChick` (which calls `Extraction`) inside modules are unsupported (and there is already a warning about it).
