### ISSUE TITLE
[warnings] Please fix OCaml warnings

### ISSUE THREAD

**Issue by ejgallego** [QuickChick/QuickChick#143]
Dear devs,

in Coq we are considering requiring plugins in the CI to use the same set of compiler flags for warnings than the main Coq tree (c.f. https://github.com/coq/coq/pull/9605 ), in particular, this means that the plugins should now compile warning-free, except for deprecation notices.

Note that some of the raised warnings are really fatal, [like missing match cases].

Please, try to fix OCaml warnings present in your codebase, thanks!

**Comment by lemonidas** [comment]
Hmmm. This will take quite a bit of effort. 
The derivation mechanism for generators/printers/shrinkers uses a generic library to abstract away from Coq internals (and changes to those) that offers a HOAS-style interface. For example, to produce a Coq function you give it a list of the names you want the variables to have and the generic library qualifies them and ensures they are fresh, using a `var` type that is opaque to the user:

`val gFun : string list -> (var list -> coq_expr) -> coq_expr`

This is used in a ton of places as follows, leading to a ton of (completely unreachable) warnings:

`gFun ["size"] (fun [size] -> ...`

We can probably create `gFun1`, `gFun2`, etc. variants to suppress them, but it will take a bit of time and effort to implement and test, which I don't have prior to the ICFP/OOPSLA deadline. Is this something that could be postponed for a couple of weeks? 

Unless @liyishuai or @Lysxia want to take lead on this, but I don't think either of them are familiar with the internals of the derivation code.

**Comment by ejgallego** [comment]
It can be postponed no rush @lemonidas , a couple of comments:
- some warnings are really signaling serious problems (like ignoring new constr constructors for primitive integers)
- in the case of your code generator you could always generate an annotation `[@warning "-8"]` to tell OCaml that you intend to use incomplete pattern matching. IMHO this would preferred over rewriting the thing.

**Comment by ejgallego** [comment]
Note the use of "should" in my message, I hope the language doesn't sound like "fix all the warnings no OR DIE".

I didn't mean it like that, but more like "hey folks, have a look at warnings, we are seeing some real problems signaled by them and we would like to get cleaner builds in the future".

**Comment by ejgallego** [comment]
Hi folks, I think QuickChick is the only dev in the CI that is having a large amount of warnings; maybe you could do a pass?

We will also do a pass when we can; for the auto-generated code please use `[@ocaml.warning "-8"]` indeed to signal that the partial pattern matching is intended.

**Comment by ejgallego** [comment]
Hi folks, I am going to disable warning 8 in the project as it is really too noisy to be of any help and Coq CI won't run with warnings anymore.

However indeed you should port your code to use a better approach, warning 8 is a _critical one_
