### ISSUE TITLE
Importing QuickChick seemingly forces constructors to state implicit arguments

### ISSUE THREAD

**Issue by YaZko** [QuickChick/QuickChick#146]
Hello
I am a bit puzzled by the following behavior.

```
Inductive foo: Type :=
| Foo: forall {A: Type}, A -> foo.
(* Notice that A is implicit in Foo *)

(* The following naturally works: *)
Definition bar: foo -> bool :=
  fun a => match a with | Foo a => true end.

(* However if I import Quickchick, it now fails *)
Require Import QuickChick.QuickChick.
Fail Definition bar': foo -> bool :=
  fun a => match a with | Foo a => true end.
(* The command has indeed failed with message:
         The constructor @Foo (in type foo) expects 2 arguments. *)
```

Note that it does not alter all implicits, the following for instance still works:
```
Definition empty (l : list unit) :=
  match l with
  | nil => true
  | _ => false
  end.
```
Is this behavior known and desirable?

This being tested with Opam's 1.0.2 package, with Coq 8.8.2.

**Comment by liyishuai** [comment]
QuickChick uses SSReflect, which [sets `Asymmetric Patterns`](https://github.com/math-comp/math-comp/blob/master/mathcomp/ssreflect/ssreflect.v#L5). The same issue occurs with `From mathcomp Require Import ssreflect.`
A quick solution is `Unset Asymmetric Patterns.` Shall we add it to our codebase as `Global`?

**Comment by liyishuai** [comment]
0969d0d1ba11537895f15e1661a865d5060d1966 fixes this issue but [broke](//travis-ci.org/QuickChick/QuickChick/jobs/502364777#L1535) the plugin.

**Comment by Lysxia** [comment]
We should really wall-off the ssreflect weirdness, or even not use it at all.
