### ISSUE TITLE
Importing QuickChick interferes with Coq Search

### ISSUE THREAD

**Issue by zoickx** [QuickChick/QuickChick#165]
After importing `QuickChick.QuickChick`, the behavior of `Search` seems to change. Namely, searching for a function (`Search (_ -> _).`) returns an error. Some other searches work like before.

### Steps to reproduce

From a clean opam installation/switch:
1. `opam repo add coq-released http://coq.inria.fr/opam/released`
2. `opam install coq-quickchick`
3. Run the following:
```
Require Import QuickChick.QuickChick.
Search (nat -> nat).
```

### Expected result

A list of definitions, containing `nat -> nat`.

### Actual result

An error message: `Error: no head constant in head search pattern`

### Additional information

Tested with
* Coq `8.8.2`, `8.9.0`, `8.9.1`
* QC `1.0.1`, `1.1.0` (corresponding to Coq versions above)

The error appears in both `coqtop` and `coqc`.

Seems to only happen when the search includes "`->`" or "`forall`". Other searches work fine.

The error message is not very well documented, only appears [here](https://github.com/coq/coq/blob/7032085c809993d6a173e51aec447c02828ae070/plugins/ssr/ssrvernac.mlg#L348) in Coq's repo.

Environment and example error:
```
$ opam --version
2.0.4

$ opam list --installed --columns=name,version
# Packages matching: installed
# Name                 # Version
base-bigarray          base
base-threads           base
base-unix              base
camlp5                 7.06.10-g84ce6cc4
conf-m4                1
coq                    8.9.1
coq-ext-lib            0.10.1
coq-mathcomp-ssreflect 1.9.0
coq-quickchick         1.1.0
coq-simple-io          1.0.0
num                    1.1
ocaml                  4.07.1
ocaml-base-compiler    4.07.1
ocaml-config           1
ocamlbuild             0.14.0
ocamlfind              1.8.0

$ cat QCSearch.v
Require Import QuickChick.QuickChick.
Search (nat -> nat).

$ coqc QCSearch.v
File "./QCSearch.v", line 2, characters 0-20:
Error: no head constant in head search pattern
```

**Comment by Lysxia** [comment]
This comes from importing `ssreflect`, which is now part of Coq's stdlib.

```
Require Import ssreflect.
Search (_ -> _).  (* Same error *)
```

It appears that ssreflect has its own `Search` which overrides the standard one, and there is a plan to remove it because of problems such as this, see also https://github.com/coq/coq/issues/8663

**Comment by zoickx** [comment]
This is no longer reproducible.
``` coq
Require Import ssreflect.
Search (_ -> _).
```
behaves as expected.
`coq 8.13.2`, `coq-mathcomp-ssreflect 1.12.0`
