### ISSUE TITLE
CI: Fix caching

### ISSUE THREAD

**Issue by Lysxia** [QuickChick/QuickChick#174]
It shouldn't take 20 minutes per CI build. Currently 10 minutes are spent on installing Coq from scratch.

**Comment by liyishuai** [comment]
Branches based on stable Coq releases should be utilizing cache if warmed up properly, unless Coq's dependencies have upgraded. `8.10` and `dev` are subject to upgrades by Coq itself, which is more frequent and require recompilation. I recall some developer recommended not to build Coq incrementally.

**Comment by liyishuai** [comment]
I sometimes delete caches because Travis fetches cache across branches, which seemed to be a [feature](https://travis-ci.community/t/fetching-cache-from-another-branch/3859?u=lys) we don’t want.

**Comment by Lysxia** [comment]
A quick re-test shows this is no longer an issue. Maybe it was just that the cache was cleared or something.
