### ISSUE TITLE
CI: Reduce output

### ISSUE THREAD

**Issue by Lysxia** [QuickChick/QuickChick#175]
The logs on travis are currently always too long, so you wait ages to get to the bottom only for travis to tell you to look at the raw log. (This might be fixed as we resolve #174.)

**Comment by liyishuai** [comment]
I did it on purpose in ocaml/ocaml-ci-scripts#271, otherwise every Coq project using that script should set a no-output timeout.

**Comment by Lysxia** [comment]
Isn't there a travis command `travis_wait` or something to get periodic output?

**Comment by liyishuai** [comment]
There is, but I'm tired of tuning the exact timeout. Verbose output does help me debugging though.

**Comment by liyishuai** [comment]
No more Travis 🎉
