### ISSUE TITLE
Support Coq 8.11

### ISSUE THREAD

**Issue by liyishuai** [QuickChick/QuickChick#188]
- [x] Create `8.11` branch
- [x] Fix compatibility issues
- [x] Publish on `extra-dev` coq/opam-coq-archive#1201
- [x] Publish on `released` coq/opam-coq-archive#1204

**Comment by spitters** [comment]
@liyishuai We're doing some experiments with property based testing for smart contracts. 
Quickchick seems useful for this.
Our work depends on meta-coq, so we'd like to move the whole development to 8.11.
Do you expect moving quickchick to 8.11 to be difficult?

We're discussing integration of quickchick in Coq Platform with @Zimmi48

**Comment by Zimmi48** [comment]
> We're discussing integration of quickchick in Coq Platform with @Zimmi48

QuickChick is already part of the Windows installer and will be a natural candidate for the platform.

It  is also part of the CI, so there should be a version which is compatible with Coq 8.11. In the Windows installer, we use 581d839e7ae989dae311e2669aa2527e6601253f.

See https://github.com/coq/coq/blob/aea8e0b9754c43f05d4c82f35ce495974cdd3501/dev/ci/ci-basic-overlay.sh#L472-L504

**Comment by liyishuai** [comment]
We now have `coq-quickchick.1.3.0` supporting Coq 8.11, and `coq-quickchick.8.11.dev` tracking `8.11` branch.
