### ISSUE TITLE
Bring back proofs of IFC case study

### ISSUE THREAD

**Issue by catalin-hritcu** [QuickChick/QuickChick#19]
We broke these proofs in the JFP submission craze (commit 2f9d25043cf), when we were adding and removing instructions. Moreover the changes on the semGen branch will also affect some of these proofs.

**Comment by catalin-hritcu** [comment]
Zoe doesn't think she'll have enough time to bring back the these proofs on her own until ICFP, can anyone help?

**Comment by maximedenes** [comment]
I'll try to take care of that.

**Comment by lemonidas** [comment]
The QuickChick/IFC repo does have proofs of a slightly more complicated machine. I don't think we also need them in this repo. Feel free to re-open if anybody thinks they're necessary.
