### ISSUE TITLE
Decimal extraction breaks in QuickChick 1.2.0

### ISSUE THREAD

**Issue by robblanco** [QuickChick/QuickChick#193]
During an upgrade from QuickChick 1.1.0 to 1.2.0 (and consequently from Coq 8.9 to Coq 8.10), I have observed that extracting `Decimal.int` while using QuickChick produces invalid OCaml code. The following minimal example exhibits the problem:

```
Require Import Coq.Init.Decimal.
From QuickChick Require Import QuickChick.

Fail Extraction TestCompile Decimal.norm.
```

Commit 15f200c0 modifies the original fix to coq/coq#7017 by defining the extraction of `Decimal.int` in terms of a module `M` originally defined in file `quickChick.ml4`. Since then, this file has been ported to the new `.mlg` format and the structure that the modified workaround depended on appears to have been lost.

A possible workaround to this bug is to overwrite the problematic `Extract Inductive` directive for `Decimal.int` with the old fix prior to extraction. However, because `Decimal` was only introduced in Coq 8.8, this cannot be done unconditionally without breaking support for Coq 8.7.

**Comment by Lysxia** [comment]
Oh yeah, QuickChick should probably not tweak extraction to depend on external files.

Another workaround is to manually add a `m.ml` file, which will just be ignored with versions of QC without that fix.

A more uniform fix might be a plugin that hacks into extraction to rename these problematic types invisibly.

Another problem that makes this difficult to fix is that on Opam, QuickChick only tracks the latest version of Coq. We do maintain older versions on this repo, so if you can afford it you can pin them locally, but this doesn't seem like a sustainable model, from either QC developers' or users' perspective.

**Comment by robblanco** [comment]
Thank you for the quick fix!

The development where I ran into this issue depends on some libraries that are not yet available for Coq 8.11, so I cannot test this change directly on it right away.

We are aiming for a single version of our code that works with a number of supported versions of Coq, and having a fix for 8.10 would be great. Without one, we could deploy a local workaround as I described above, though this would certainly break our 8.7 build and would be of no use for anything other than 8.10, as #194 already merges your fix into 8.11.

**Comment by liyishuai** [comment]
The changes are reflected now in `coq-quickchick.8.10.dev`, and soon in 1.2.1.

**Comment by robblanco** [comment]
Wonderful, thank you again! I test it later today, then.

**Comment by robblanco** [comment]
Done testing. The fix works correctly as expected.

**Comment by Lysxia** [comment]
Awesome! Thanks for testing!

**Comment by robblanco** [comment]
And thank you again for the quick fix! I don't know how you handle the closing of issues, but this one looks solved as far as I can tell.

**Comment by Lysxia** [comment]
I also think it's fine to close.

**Comment by liyishuai** [comment]
`coq-quickchick.1.2.1` is on OPAM now.
