### ISSUE TITLE
Scrap the boilerplate when invoking plugin

### ISSUE THREAD

**Issue by catalin-hritcu** [QuickChick/QuickChick#2]
Even the simplest example of using the plugin looks like this:

    Definition test0 :=
      showResult (quickCheck removeP).
    QuickCheck test0.

Ideally, I would like to write only

    QuickCheck removeP.

**Comment by maximedenes** [comment]
I know how to do this.

**Comment by maximedenes** [comment]
Alright, I had forgotten that this piece of code needs to resolve the implicit arguments of quickCheck, so it is more complicated than I thought. We should be able to do it, though.

**Comment by maximedenes** [comment]
I've improved the current QuickCheck command to take a term representing a property directly. However, in QuickChick/examples/RedBlack/testing.v, I see that QuickCheck was called with a custom "showDiscards" function (instead of "showResult"). This is no longer possible with the new command. Should I simply remove showDiscards? Or should we move it to the main framework and pass a flag to the QuickCheck command?

**Comment by catalin-hritcu** [comment]
Moving it to the main framework and passing a flag to the `QuickCheck` command would work in this particular case. In general, how about leaving the `QuickCheck` command alone though (i.e. working with the default arguments, as close as possible to the `quickCheck` function), and providing another `QuickCheckWith` command corresponding to the `quickCheckWith` function. The `quickCheckWith` function takes some `Args`, one of which is called `chatty` and is currently unused as far as I can see, and maybe displaying discard information should be part of that. Otherwise, we could have a special flag for the discard rates. We could also try to mimic Haskell QuickCheck, but I'm not sure it's flexible enough in this respect.
[I do get notifications for github comments, but anyway, thanks for the heads-up]

**Comment by maximedenes** [comment]
Done.

**Comment by catalin-hritcu** [comment]
Cool, thanks a lot. I've filed the `showDiscards` related part as part of a larger issue on printing (#29). Not urgent though.

**Comment by catalin-hritcu** [comment]
Actually, I've just noticed that Driver.v in `ifc-basic` and `IFC` were both broken, and I can only partially fix them. In particular they rely on running special functions for mutation testing. So do we want to also turn those into commands? Or do we want a command that just prints a string? :)

**Comment by maximedenes** [comment]
The plugin now exports 6 commands that should cover these use cases. I started to adapt examples/ifc-basic/testing.v, but didn't put it back in the Makefile until you review it.

**Comment by catalin-hritcu** [comment]
Made IFC/Driver.v compile again using MutateCheckMany. Closing.
