### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.13

### ISSUE THREAD

**Issue by gares** [QuickChick/QuickChick#207]
The Coq team is planning to release Coq 8.13-beta1 on December 7, 2020
and Coq 8.13.0 on January 7, 2020.

Your project is currently scheduled for being bundled in the Windows installer.

We are currently testing commit 63aa0581644e9117a9403de25a66edfc43a53c9a
on branch https://github.com/QuickChick/QuickChick/tree/master
but we would like to ship a released version instead (a tag in git's slang).

Could you please tag that commit, or communicate us any other tag
that works with the Coq branch v8.13 at the *latest* 15 days before the
date of the final release?

Thanks!
CC: https://github.com/coq/coq/issues/12334

**Comment by liyishuai** [comment]
https://github.com/QuickChick/QuickChick/releases/tag/v1.5.0

**Comment by gares** [comment]
thanks!
