### ISSUE TITLE
Is it possible for Quickchick to use Coq's message-printing facilities somehow?

### ISSUE THREAD

**Issue by anton-trunov** [QuickChick/QuickChick#225]
Because QC prints on stdout it's not possible to use Alectryon with it, please see https://github.com/cpitclaudel/alectryon/issues/43.

Since QC works on extracted OCaml code I don't know how hard (if possible) it would be to use the Coq API to provide feedback.

**Comment by cpitclaudel** [comment]
Specifically, the problematic output is this one:

```
QuickChecking (fun _ : bool => true)
/home/clement/.opam/coq-8.12/bin/ocamldep.opt -modules QuickChick458399.ml > QuickChick458399.ml.depends
/home/clement/.opam/coq-8.12/bin/ocamldep.opt -modules QuickChick458399.mli > QuickChick458399.mli.depends
/home/clement/.opam/coq-8.12/bin/ocamlc.opt -c -w -3 -o QuickChick458399.cmi QuickChick458399.mli
/home/clement/.opam/coq-8.12/bin/ocamlopt.opt -c -w -3 -o QuickChick458399.cmx QuickChick458399.ml
/home/clement/.opam/coq-8.12/bin/ocamlopt.opt unix.cmxa QuickChick458399.cmx -o QuickChick458399.native
```

The `+++ Passed 10000 tests (0 discards)` seems to be printed separately, in a way that SerAPI understands; it would be great if the rest of the output could also be printed that way.

(I wonder how this works with CoqIDE; I would expect it to also break the XML that CoqIDE reads)

**Comment by Lysxia** [comment]
Indeed we use the API but only for the output of running the executable. It shouldn't be hard to also capture the build output.

**Comment by cpitclaudel** [comment]
(Or it would be nice if SerAPI could do the same thing as CoqIDE; I can see how the build output may not be desirable to show to users by default).  

CC @ejgallego: Hey Emilio, quick question.  If I put 

```
From QuickChick Require Import QuickChick.
QuickChick (fun _ : bool => true).
```

into CoqIDE then one line of output (`+++ Passed 10000 tests (0 discards)`) appears in the response window, and some debugging info appears on the terminal that CoqIDE started from (`…/ocamlopt.opt unix.cmxa QuickChickc98a65.cmx -o QuickChickc98a65.native`).  This is the ideal behavior.  But if I use SerAPI, then the debugging info is mixed with SerAPI's regular output:

```
("query0"("Add"()"From QuickChick Require Import QuickChick.\nQuickChick (fun _ : bool => true)."))
("query1"("Exec""2"))
("query2"("Query"(("sid""2"))"EGoals"))
("query3"("Exec""3"))
```

```
…
(Answer query3 Ack)
(Feedback((doc_id 0)(span_id 3)(route 0)(contents(ProcessingIn master))))
(Feedback((doc_id 0)(span_id 2)(route 0)(contents Processed)))
QuickChecking (fun _ : bool => true)
/home/clement/.opam/coq-8.12/bin/ocamldep.opt -modules QuickChickc98a65.ml > QuickChickc98a65.ml.depends
/home/clement/.opam/coq-8.12/bin/ocamldep.opt -modules QuickChickc98a65.mli > QuickChickc98a65.mli.depends
/home/clement/.opam/coq-8.12/bin/ocamlc.opt -c -w -3 -o QuickChickc98a65.cmi QuickChickc98a65.mli
/home/clement/.opam/coq-8.12/bin/ocamlopt.opt -c -w -3 -o QuickChickc98a65.cmx QuickChickc98a65.ml
/home/clement/.opam/coq-8.12/bin/ocamlopt.opt unix.cmxa QuickChickc98a65.cmx -o QuickChickc98a65.native
(Feedback((doc_id 0)(span_id 3)(route 0)(contents(Message(level Info)(loc())(pp(Pp_string"+++ Passed 10000 tests (0 discards)"))(str"+++ Passed 10000 tests (0 discards)")))))
(Feedback((doc_id 0)(span_id 3)(route 0)(contents Processed)))
(Answer query3 Completed)
(Answer EOF Ack)
(Answer EOF Completed)
```

Quickchick's response message is handled as feedback message, and the rest of QuickChick's output but the rest is mixed with SerAPIs stuff.  This all makes sense given how SerAPI works, but I don't understand why it doesn't happen with CoqIDE as well — does CoqIDE use a separate channel for communication with Coq? Maybe a socket instead of stdin/stdout?  Should we do the same with SerAPI?

**Comment by ejgallego** [comment]
Hey @cpitclaudel , indeed CoqIDE uses a socket system, whereas SerAPI by default uses stdin/stdout so hence the issue.

One of the pain points of the CoqIDE protocol indeed was the socket setup, so initially only that mode of communication was used, but it wouldn't be hard to add an option to SerAPI to use sockets for communication if we want; the large refactoring was already done when we added fork. In fact in 8.13 you can already do:
```
(Fork (fifo_in "/tmp/sp01_in") (fifo_out "/tmp/sp01_out"))
```
and that will create fifos and fork serapi. If you wanna expose this as a cmdline interface please open a ticket.

Generally, the current Coq plugin model does not grant access to stdin / stdout as indeed uncoordinated access is hard and there are portability issues. But on the other hand this is not satisfactory as many plugins need actually access to run external commands.

Isabelle has a nice API for this, which SMT solvers etc... can use, so hopefully we can provide this extended facilities to Coq plugins some day, which would nicely fit QuickChick IMO.

Moreover, Coq already knows how to handle the build of .ml files [used by the native backend], so we could indeed expose a higher level API for QuickChick and other users allowing the control of ML compilation.
