### ISSUE TITLE
Our specs are polluted by default value cases

### ISSUE THREAD

**Issue by catalin-hritcu** [QuickChick/QuickChick#23]
For instance:

```
    forall {A} (l: list A) (def : A),
      (semGen (elements def l)) <--> (fun e => List.In e l \/ (l = nil /\ e = def)).
```

These default arguments weren't needed in Haskell, where functions can just fail in such cases. In Coq we had the choice between making Gen contain option (and that would have been tedious, right?) and taking default arguments. One way to get rid of these defaults would be to use dependent types, but in Coq that means computing with proofs, which is horrible (F\* gets this right, but Coq doesn't!).

One suggestion by Leo would be to turn this lemma into two:

```
    forall {A} (l: list A) (def : A),
      l <> nil ->
      (semGen (elements def l)) <--> (fun e => List.In e l).
```

and

```
    forall {A} (def : A),
      (semGen (elements def nil)) <--> eq def.
```

While this seems indeed like an improvement, I still wonder what's the problem with incorporating the error monad into Gen. We could use partial correctness specs that only talk about the Some case, so at the spec level I think we would get the cleanest thing without dependent types.

**Comment by catalin-hritcu** [comment]
Ah, only now I see it's hard to do partial correctness specs for our spec style, and would basically need the semantics return an option Ensamble, so the errors would permeate everything, which is silly and we don't want. OK, so nevermind, it's either Leo style or dependent types.

**Comment by lemonidas** [comment]
The current version of the specs has actually proved to be modular, as we've used it to automatically produce proofs of correctness for relatively complicated generators.

**Comment by catalin-hritcu** [comment]
@lemonidas Using defaults seems indeed the right decision in retrospect. They do the same in hs-to-coq, just with a bit of extra type class magic to instantiate the defaults. Wondering if that type class magic could be stolen here?
