### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.14

### ISSUE THREAD

**Issue by MSoegtropIMC** [QuickChick/QuickChick#236]
The Coq team released Coq 8.14+rc1 on September 17, 2021
and plans to release Coq 8.14.0 before October 31, 2021.
A corresponding Coq Platform releases should be released before November 30, 2021.
It can be dealyed in case of difficulties until January 31, 2022, but this should be an exception.

Coq CI is currently testing commit 80f4c88e949f25b6167993ce6a7e34ed29ca44cb
on branch https://github.com/QuickChick/QuickChick/tree/master
but we would like to ship a released version instead (a tag in git's slang).

Coq Platform is currently *not testing* this package!

Could you please create a tag, or communicate us any existing tag that works with
Coq branch v8.14, preferably 15 days before November 30, 2021
or earlier? In case we might have to delay the Coq Platform release cause of issues with
your project, we would prefer to be informed about the situation as early as possible.

Thanks!

P.S.: this issue has been creates semi-automatically.

CC: https://github.com/coq/platform/issues/139

**Comment by liyishuai** [comment]
[v1.5.1](https://github.com/QuickChick/QuickChick/tree/v1.5.1) has been tested against Coq 8.14-rc1.

**Comment by MSoegtropIMC** [comment]
Thanks - tested fine in Coq Platform (including the opam file from https://github.com/coq/opam-coq-archive/pull/1819)

**Comment by MSoegtropIMC** [comment]
I reopened this to ask if Coq Platform 2021.11 (still in processing) should use tag 1.6.0.

**Comment by Lysxia** [comment]
Yes, if you can update, please do :)

**Comment by MSoegtropIMC** [comment]
OK, I will update to 1.6.0 then. Please leave this issue open until I did the update - I will close it then.
