### ISSUE TITLE
Issues using QuickChick on Windows: does it require perl?

### ISSUE THREAD

**Issue by MSoegtropIMC** [QuickChick/QuickChick#237]
I have the following QuickChick usage report with Coq Platform: (https://github.com/coq/platform/issues/95).

I was not aware that QuickChick uses perl. Does it? If you explain me the background we can likely fix this together, but installing perl for QuickChick would be extremely heavy. Maybe I can help you to do whatever you need to do with awk or so.

**Comment by liyishuai** [comment]
Once ocaml/opam-repository#19621 gets merged we can substitute Perl with cppo. Not sure why CI failed there.

**Comment by Lysxia** [comment]
Sorry about that. I introduced those scripts to generate compatibility shims to build QuickChick with multiple versions of Coq (instead of maintaining multiple branches). QuickChick has actually always depended on perl, to apply a fix to extracted code in the `QuickChick` command in Coq and in the standalone tool, so I'm surprised this hasn't been caught before. The main difference now is that it is needed at build time. We can fix this so it all uses OCaml to reduce our dependency footprint.

**Comment by MSoegtropIMC** [comment]
Possibly it hasn't been tested before on Windows - at least not with the installer.

As I said: awk is much more light weight than perl and usually sufficient for simple text processing. I usually either use sed or awk or write some program in a proper language. If you need help with porting from perl to awk, please let me know.

**Comment by MSoegtropIMC** [comment]
Just wanted to note that my previous comment was nonsense: we do test QuickChick with the Coq Platform Smoke Test Kit, also on Windows for installed Coq Platform (not built from sources).

I tested it on my private machine and the Smoke Test Kit does work. I have perl installed but not in PATH. Does QuickChick do something fancy to find perl?

I didn't see the `cppo` comment before - it would indeed be great if you could remove a runtime requirement on perl.

**Comment by Lysxia** [comment]
That's now done! Just need a release.

**Comment by spitters** [comment]
Has this been included in a release?
One of my students hit this issue recently.

**Comment by MSoegtropIMC** [comment]
Probably not - Coq Platform is still in tag 1.5.1. I will take a note in the tracker.

**Comment by MSoegtropIMC** [comment]
I reopened (https://github.com/QuickChick/QuickChick/issues/236) to discuss this.

**Comment by Lysxia** [comment]
You're on time since I just released 1.6.0 today :)

**Comment by spitters** [comment]
I don't see it, but I imagine I'll just need to be patient?
https://github.com/QuickChick/QuickChick/releases

**Comment by liyishuai** [comment]
https://github.com/QuickChick/QuickChick/releases/tag/v1.6.0
