### ISSUE TITLE
Report compiler errors to the user

### ISSUE THREAD

**Issue by anton-trunov** [QuickChick/QuickChick#257]
When interfacing QC with untested OCaml code I often get errors like
```
Error:
Could not compile test program: /var/folders/qy/cwhzbpsj75g81gtv3hjzn4mw0000gn/T/QuickChick/202430/QuickChickad4aab.ml
```

then I have to do something like
```
cd /var/folders/qy/cwhzbpsj75g81gtv3hjzn4mw0000gn/T/QuickChick/202430/
dune build
```
to see the exact error (which almost all the time is just a typo) and then do `popd` to go to the project directory and fix the issue and build again and then repeat the cycle :)

I'd be much happier if I could see the compilation error right away.

**Comment by Lysxia** [comment]
#258 should fix this :)
