### ISSUE TITLE
Hook <--> up to the generalized rewriting framework

### ISSUE THREAD

**Issue by catalin-hritcu** [QuickChick/QuickChick#26]
We should hook <--> up to the generalized rewriting framework.
I was trying to do this for `semReturn` and there are still some scars left in the code:
```
   Lemma semReturn : forall A (x : A),
                       semGen (returnGen x) <--> eq x.
   Proof. (* this kind of proof should be "trivial by rewriting",
          but this doesn't quite work as easy at it should *)
     move => A x. rewrite /semGen.
     (* was hoping to do the rest by rewriting: setoid_rewrite semReturnSize. *)
     pose proof (semReturnSize x) as G. unfold set_eq in G.
     (* setoid_rewrite G. -- failed constraints *)
     move => a /=. split.
     - move => [size H]. (* or rewrite -> G in H. exact H. *)
       rewrite <- G. exact H.
     - move => H. exists 0. by rewrite G.
   Qed.
```

**Comment by maximedenes** [comment]
I'm not sure to follow everything here. The rewrite fails because semReturnSize is stated with a  forall size (in prenex form), whereas semGen packages the size behind an exists. Did you expect that gap to be filled automatically by generalized rewriting?

**Comment by catalin-hritcu** [comment]
Sorry, but I don't remember the details of this. All I have a this point is a general feeling that generalized rewriting for <--> could simplify a lot of the super boring proofs.

**Comment by catalin-hritcu** [comment]
I think Maxime's set library is solved this, although we're might still be missing some instances needed for rewriting. Closing.
