### ISSUE TITLE
Fatal error: exception Invalid_argument("Random.int") for simple generator

### ISSUE THREAD

**Issue by dhilst** [QuickChick/QuickChick#265]
I'm trying the simple example below

```ocaml
From QuickChick Require Import QuickChick.
Import QcDefaultNotation. Open Scope qc_scope.
Import GenLow GenHigh.
Set Warnings "-extraction-opaque-accessed,-extraction".

Require Import List ZArith Strings.Ascii Strings.String.

Require Import mathcomp.ssreflect.ssreflect.
From mathcomp Require Import seq ssreflect ssrbool ssrnat eqtype.

Open Scope Z_scope.
Definition genPosInt : G Z :=
  choose (0%Z, (Z.pow 2 31) - 1).

Sample genPosInt.
```

This gives me the following error

```
Fatal error: exception Invalid_argument("Random.int")
```

Am I missing something?

To explain my use case, I have some functions defined for positive OCaml ints (this is why `2^31-1`) and want to write some property tests for them. This generator would be used to provide random ints as input.

I could check that `2^29` works but `2^30` don't

```ocaml
Sample (choose (0, Z.pow 2 29)). (* This works *)
Sample (choose (0, Z.pow 2 30)). (* This fails with Invalid_argument("Random.int") *)
```

**Comment by Lysxia** [comment]
It's a problem on QuickChick's side. We are using `Random.int`, and according to the `Random` module documentation, the bound must be less than `2^30`. There is a `Random.full_int` we can use since OCaml 4.13, so you could try overriding extraction of `randomRZ` with that.

**Comment by dhilst** [comment]
I tried this

```
Axiom randomRZ : int -> int.
Extract Constant randomRZ => "Random.full_int".
```

But it didn't help. I'm very new to Coq so I'm felling that I'm missing something obvious. I searched for `randomRZ` definition with `Locate` and searched on QuickChick source code using github search but couldn't find anything.

**Comment by Lysxia** [comment]
Don't worry, it's not obvious! Add this at the top of your file:

```coq
Extract Constant randomRInt  =>
  "(fun (x,y) r -> if y < x then failwith ""choose called with unordered arguments"" else  (x + (Random.State.full_int r (y - x + 1)), r))".
```

This comes from the following line

https://github.com/QuickChick/QuickChick/blob/0ff249f3f23aab7dfba4835227e891dbd0a3a246/src/ExtractionQC.v.cppo#L112

and `randomRInt` is used in the `Choose` instance for `Z`:

https://github.com/QuickChick/QuickChick/blob/0ff249f3f23aab7dfba4835227e891dbd0a3a246/src/RandomQC.v#L774

**Comment by dhilst** [comment]
Thank you @Lysxia 

I can confirm that this worked like a charm 

```
From QuickChick Require Import QuickChick.
Import QcDefaultNotation. Open Scope qc_scope.
Import GenLow GenHigh.
Set Warnings "-extraction-opaque-accessed,-extraction".

Require Import List ZArith Strings.Ascii Strings.String.

Require Import mathcomp.ssreflect.ssreflect.
From mathcomp Require Import seq ssreflect ssrbool ssrnat eqtype.

Extract Constant randomRInt  =>
  "(fun (x,y) r -> if y < x then failwith ""choose called with unordered arguments"" else  (x + (Random.State.full_int r (y - x + 1)), r))".

Open Scope Z_scope.

Sample (choose (0, (Z.pow 2 31) - 1)). (* This fails with Invalid_argument("Random.int") *)

```
