### ISSUE TITLE
Dune-based builds fail with 'I cannot find the root of the current workspace/project'

### ISSUE THREAD

**Issue by anton-trunov** [QuickChick/QuickChick#287]
Looks like this is since Dune v3.0.

I get the following error message:

```
Error:
Could not compile test program: /var/folders/qy/cwhzbpsj75g81gtv3hjzn4mw0000gn/T/QuickChick/105617/QuickChick032d74.ml

Build stderr:
Error: I cannot find the root of the current workspace/project.
If you would like to create a new dune project, you can type:

    dune init project NAME

Otherwise, please make sure to run dune inside an existing project or
workspace. For more information about how dune identifies the root of the
current workspace/project, please refer to
https://dune.readthedocs.io/en/stable/usage.html#finding-the-root
```

My dune version is

```shell
$ dune --version
3.2.0
```

Also, let me link a related issue here: #259

**Comment by anton-trunov** [comment]
Btw, something like this fixes the issue for me: https://github.com/QuickChick/QuickChick/compare/master...anton-trunov:workaround-for-dune-project-root-issue?expand=1

**Comment by Alizter** [comment]
cc @rgrinberg any idea what is going on with root detection here?

**Comment by rgrinberg** [comment]
As far as I can see, dune is being ran without a dune-project, dune-workspace, or an explicit root. So it rightfully complained.

**Comment by Lysxia** [comment]
That's also my understanding.
