### ISSUE TITLE
Bad installation target for quickChick tool

### ISSUE THREAD

**Issue by SnarkBoojum** [QuickChick/QuickChick#296]
The toplevel Makefile tries to install quickChick to the same directory as coqc.

That means it doesn't respect DESTDIR, and that is a problem when packaging QuickChick.

I propose the following patch:
```
--- coq-quickchick.orig/Makefile
+++ coq-quickchick/Makefile
@@ -8,7 +8,7 @@
                   $(QCTOOL_DIR)/quickChickToolLexer.mll \
                   $(QCTOOL_DIR)/quickChickToolParser.mly
 
-INSTALLDIR?=$(dir $(shell which coqc))
+INSTALLDIR?=$(DESTDIR)$(dir $(shell which coqc))
 
 # Here is a hack to make $(eval $(shell work
 # (copied from coq_makefile generated stuff):
@@ -34,6 +34,7 @@
 install: all
        $(V)$(MAKE) -f Makefile.coq install > $(TEMPFILE)
 # Manually copying the remaining files
+       $(V)mkdir -p $(INSTALLDIR)
        $(V)cp $(QCTOOL_DIR)/$(QCTOOL_EXE) $(INSTALLDIR)/quickChick
 #       $(V)cp src/quickChickLib.cmx $(COQLIB)/user-contrib/QuickChick
 #       $(V)cp src/quickChickLib.o $(COQLIB)/user-contrib/QuickChick
```

**Comment by Lysxia** [comment]
Should the rest of the path still be `$(dir $(shell which coqc))`? That's an absolute path so it doesn't seem right to concatenate it with `$(DESTDIR)`.

**Comment by SnarkBoojum** [comment]
Well, it works here, and prepending DESTDIR is what is usually done...

**Comment by Lysxia** [comment]
OK I was just not familiar with DESTDIR. It's supposed to be a temporary location for staging installs, which is why it's meant to be prepended it to an absolute path. Would you like to make that PR, and I'll just accept it?

**Comment by Lysxia** [comment]
Fixed because QuickChick is now being installed via dune.
