### ISSUE TITLE
Certificate producing meta-program constructing generators for basic datatypes

### ISSUE THREAD

**Issue by catalin-hritcu** [QuickChick/QuickChick#31]
I think it would make our story stronger if we could claim that our framework is also useful for certificate producing meta-programs, that is, commands written in OCaml that produce artifacts like generators together with their correctness proofs in our framework.

The canonical example I have in mind is an OCaml command for obtaining a default generator for any basic inductive type (basically building generators for various kinds of trees); this command would also produce a proof that the produced generator is complete for the given type. This would work very much like induction principles in Coq: if your datatype is simple enough you can get one for free.

**Comment by catalin-hritcu** [comment]
This was suggested by François Pottier when he saw out naive generator for trees (not necessarily satisfying the red-black property), and I completely agree, nobody should have to write this kind of boring code again and again. So such a meta-program would clearly be very useful; making it additionally produce certificates is just the cherry on top of the cake, and would also strengthen our story for the paper a bit.

**Comment by catalin-hritcu** [comment]
Li-yao recently implemented something like this recently for Luck; his code is in our private repo:
`<quickchick-gforge>/generator-language/src/Core/Types/Generator.hs` and we could probably make it available sooner if anyone is interested in implementing this. It is based on the following Erlang paper:
A PropEr Integration of Types and Function Specifications with PBT, by Manolis Papadakis and Konstantinos Sagonas (http://proper.softlab.ntua.gr/papers/proper_types.pdf)
Porting this to Coq would be useful even if we don't do the "certificate producing" part yet.

**Comment by lemonidas** [comment]
[:)](https://lemonidas.github.io/pdf/GeneratingGoodGenerators.pdf)
