### ISSUE TITLE
Please create a tag for Coq 8.17 in Coq Platform 2023.03

### ISSUE THREAD

**Issue by MSoegtropIMC** [QuickChick/QuickChick#318]
The Coq team released Coq `8.17+rc1` on December 29th, 2022 and plans to release Coq 8.17.0 around March 7th, 2023.
The corresponding Coq Platform release `2023.03` should be released before **April 14th, 2023**.
It can be delayed in case of difficulties until June 30, 2023, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (1.6.4) **does not work** with Coq `8.17+rc1`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit 81d8ffe90d6934ccbadb0c1468f8c3bc3627cc81 on repository https://github.com/QuickChick/QuickChick - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.17, **preferably before March 21st, 2023**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before March 21st, 2023, it will be included in an early Coq Platform beta release of the for Coq 8.17+rc1.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.17~2023.03+preview1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.17~2023.03+preview1.sh) which already supports Coq version `8.17+rc1` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/335

**Comment by MSoegtropIMC** [comment]
@lemonidas @catalin-hritcu @zoep : I would appreciate a status update and/or ETA on this.

**Comment by Lysxia** [comment]
@lemonidas Should we aim to get 2.0 ready for this Coq platform release (the library is buildable now but maybe we want to make sure that it works with `tutorial/` and the QC book?), or should I just make a minor release with the current master branch?

**Comment by lemonidas** [comment]
Let's push for a 2.0 release - if the only thing failing are the proof derivations we can comment them out until we get around to them.

**Comment by MSoegtropIMC** [comment]
May I ask if there is a status update and/or an ETA?

**Comment by MSoegtropIMC** [comment]
@Lysxia @lemonidas : please note that this the **only** Coq Platform "full"-level package for which I don't yet have an ETA for a 8.17 compatible release. The only other "full-level" package without a 8.17 release is MetaCoq, for which I have an ETA of this week.

I would like to create a Coq Platform 2023.03 beta today or tomorrow - my current status is that I have to remove QuickChick in the beta release. Since you noted above that you plan to do a new major release, it does not make a lot of sense to include a master commit into the beta.

**Comment by lemonidas** [comment]
We should have a 2.0 release by the end of the day though.

**Comment by lemonidas** [comment]
Feel free to use this release: https://github.com/QuickChick/QuickChick/releases/tag/v.2.0

Will make the opam PR soon.

**Comment by MSoegtropIMC** [comment]
Thanks! I Updated the 8.17 pick in Coq Platform 2023.03 to coq-quickchick.2.0.0 and close this issue.

**Comment by MSoegtropIMC** [comment]
I just tested 1.6.5 and this does work fine, so I will switch back to 1.6.5 (on all platforms) for the time beeing.

**Comment by Lysxia** [comment]
I'm not sure how to troubleshoot that error off the top of my head either. 1.6.5 seems like the best workaround for the moment.

**Comment by MSoegtropIMC** [comment]
Confirming that I used 1.6.5 and closing.
