### ISSUE TITLE
Type error installing QuickChick with Coq 8.5

### ISSUE THREAD

**Issue by cdstanford** [QuickChick/QuickChick#36]
While installing QuickChick, downloading the coq8.5 branch and running `make`, I get the following type error:

```
File "src/derive.ml4", line 505, characters 14-16:
Error: This expression has type unit but an expression was expected of type string
Makefile.coq:424: recipe for target 'src/derive.cmo' failed
make[1]: *** [src/derive.cmo] Error 2
make[1]: Leaving directory '/home/caleb/git/QuickChick'
Makefile:15: recipe for target 'plugin' failed
make: *** [plugin] Error 2
```

I have coq version 8.5pl3, ocaml 4.02.3, opam 1.2.2, and math-comp ssreflect 1.6:
```
$ coqc --version
The Coq Proof Assistant, version 8.5pl3 (November 2016)
compiled on Nov 28 2016 12:27:29 with OCaml 4.02.3
$ ocaml -version
The OCaml toplevel, version 4.02.3
$ opam --version
1.2.2
$ sudo opam list
[...]
coq-mathcomp-ssreflect    1.6  Small Scale Reflection
```

Any idea what is causing the type error here, and how this could be fixed?

Thanks!
Caleb

**Comment by lastland** [comment]
Hi, I have got the same problem with Coq 8.5pl2 and OCaml 4.03.0.

**Comment by zoep** [comment]
Hi everyone,

I'm afraid I introduced the error in my latest commit. It should be fixed now. 

Best,
Zoe

**Comment by lastland** [comment]
Hi Zoe, it works for me now. Thanks!
