### ISSUE TITLE
Deriving fails when reusing a bound variable

### ISSUE THREAD

**Issue by lweqx** [QuickChick/QuickChick#377]
The following example fails with the following error `Can't find: SomethingThatAlreadyExists0` :
```coq
From QuickChick Require Import QuickChick.

Definition SomethingThatAlreadyExists : nat := 0.

Inductive single : bool -> Prop :=
  | Ctor (n : nat) : single true.
Inductive relation : single true -> Prop :=
  | R1 : forall SomethingThatAlreadyExists,
      relation (Ctor SomethingThatAlreadyExists).
Derive ArbitrarySizedSuchThat for (fun a => relation a).
```

**Comment by lemonidas** [comment]
Something is not being qualified correctly in the derivation - it's hard to pin down, but I'm working on it.

**Comment by lweqx** [comment]
I don't a high confidence in what follows, but I think it boils down to:
- `handle_branch` calls (unifyQC.ml.cppo, line 648) `bind` (from arbitrarySizedST.ml, line 35) to generate `buildGen arbitrary (fun x => Ctor x)`. It tries to use  `SomethingThatAlreadyExists` as the name`x`. However this name is already bound in the environment, so `gFun` will instead use the next available identifier: `SomethingThatAlreadyExists0`. `buildGen arbitrary (fun SomethingThatAlreadyExists0 => Ctor SomethingThatAlreadyExists0)` will thus be generated. Control returns to `handle_branch` via the continuation (unifyQC.ml.cppo, line 632, then line 649, then line 1707), with `res_range = "Ctor (Unknown SomethingThatAlreadyExists0)"`. Execution flows to `range_to_coq_expr`, which ends up looks for the result range in the `umap`. `SomethingThatAlreadyExists0` was never actually added to the `umap`, resulting in the "Can't find: SomethingThatAlreadyExists0" error.

What do you think about making the following changes to `process_checks` ? This is the original code:
```coq
  let process_checks bind x opt g (cont : var -> coq_expr) : coq_expr =
    msg_debug (str ("Processing checks for variable: " ^ (Unknown.to_string x)) ++ fnl ());
    match lookup_checks (DTyVar x) !cmap with
    | Some checks -> 
       (* Remove checks from cmap *)
       msg_debug (str "Actual checks needed" ++ fnl ());
       cmap := CMap.remove (DTyVar x) !cmap;
       umap := fixVariable x !umap;
       bind true
         (stMaybe opt g (var_to_string x) checks)
         (var_to_string x)
         (fun x -> cont x)
    | None ->
       umap := fixVariable x !umap;
       bind opt g (var_to_string x) (fun x -> cont x)
  in
```
to:
```coq
  let process_checks bind x opt g (cont : var -> coq_expr) : coq_expr =
    msg_debug (str ("Processing checks for variable: " ^ (Unknown.to_string x)) ++ fnl ());

    let continuation x' =
      let r = umfind x !umap in
      (*umap := UM.remove x !umap;*)
      umap := UM.add x' r !umap;
      cont x' in
    
    match lookup_checks (DTyVar x) !cmap with
    | Some checks -> 
       (* Remove checks from cmap *)
       msg_debug (str "Actual checks needed" ++ fnl ());
       cmap := CMap.remove (DTyVar x) !cmap;
       umap := fixVariable x !umap;
       bind true
         (stMaybe opt g (var_to_string x) checks)
         (var_to_string x)
         continuation
    | None ->
       umap := fixVariable x !umap;
       bind opt g (var_to_string x)
       continuation
  in
```
The example with this change, the example works. It crashes if I don't remove `x` from `umap`, I did not (yet?) investigate why exactly.

**Comment by lemonidas** [comment]
Close, but not quite right - the problem is that it would still fail in the `Some checks` case, if that were used. 
We'd need to refactor the bind to allow using the continuation variable as well somehow, as the checks in stMaybe should be using the qualified x. However, the cmap is not really used for its original purpose (handling negations by filtering in the end), so it might be doable. 

Instead of fixing x, removing it, and then adding x', the correct approach would probably be to fix x, add x' mapping to whatever x points to, and then map x to x'. That should preserve the internal invariants. The fixing of the variable should _probably_ also happen inside the continuation.

I'll need to do quite a bit of testing, but I'm working on it today.

**Comment by lemonidas** [comment]
@lweqx check if [this](https://github.com/QuickChick/QuickChick/tree/fix-377) branch fixes your issues!

**Comment by lweqx** [comment]
Works flawlessly for my use case, thank you!
