### ISSUE TITLE
Publish release compatible with Coq 8.20

### ISSUE THREAD

**Issue by SnarkBoojum** [QuickChick/QuickChick#391]
I would like to update the Coq packages in Debian, so I'm looking for a set of coherent upstream releases.

**Comment by SnarkBoojum** [comment]
Uh... could you re-open this issue and only close it when the new version is actually published? The point was to be notified when it was available for packaging... Thanks.

**Comment by liyishuai** [comment]
- [ ] coq/opam#3159

**Comment by liyishuai** [comment]
v2.0.4 is on OPAM now.
