### ISSUE TITLE
choose with invalid interval

### ISSUE THREAD

**Issue by dschoepe** [QuickChick/QuickChick#47]
I noticed that when calling `choose` with an empty interval, such as `choose (1, 0)`, QuickChick fails with the message `Error: Exited with status 2`. I suppose an ideal solution would be to rule out such calls statically (potentially using typeclass magic?), however that may be tricky to implement. This is somewhat analogous to a version of `elements` without a default, however, this would make choose very cumbersome to use.

In any case, I think choose should produce a more helpful error message in such cases.

**Comment by liyishuai** [comment]
An easier patch is to treat `choose (1, 0)` as `choose (0, 1)`, which doesn't require modification of current type definitions.

**Comment by liyishuai** [comment]
This issue is solved by https://github.com/QuickChick/QuickChick/commit/e0adc7c2ec511ff5ecaa69728c7c1160967bd9f6.
