### ISSUE TITLE
Unconstrained instance resolution loops

### ISSUE THREAD

**Issue by Lysxia** [QuickChick/QuickChick#51]
Here's a minimal example.

```
Require Import QuickChick.
Check arbitrary.
```

One workaround is to always pass arguments explicitly, but that doesn't take advantage of type classes, and it is prone to forgetful mistakes.

- I suppose Coq is repeatedly picking some blanket instances lying around. Wouldn't it be better to have them not in scope by default, or to reduce their priority to avoid these situations?

- What is the usual way out when Coq gets stuck like that? Currently in Proof General, I'm killing it (`C-x k *coq*`) but it's a chore to jump back in the previous location.

- Is Coq's instance resolution algorithm just a big backtracking search? Are there ways to customize it beyond priority numbers?

**Comment by liyishuai** [comment]
`Require Import QuickChick.` doesn't work on my machine:
> Error: Unable to locate library QuickChick.

However, the following code:
```
Require Import QuickChick.Classes.
Check arbitrary.
```
prints, as expected:
```
arbitrary
     : GenLow.GenLow.G ?A
where
?A : [ |- Type] 
?Gen : [ |- Gen ?A] 
```
Which branch are you working with? I'm currently on `coq.8.6`.

**Comment by Lysxia** [comment]
I'm on `master`.

Oh it looks like `QuickChick` alone is a quirk due to my working in the QuickChick repository.

I get the same output as you do with `QuickChick.Classes`. What about `QuickChick.QuickChick`?

**Comment by liyishuai** [comment]
I have replicated this problem. By `Set Typeclasses Debug.` I got the following trace:
```
Debug: 1: looking for (Gen ?A) with backtracking
Debug: 1.1: simple apply @genOption on (Gen ?A), 1 subgoal(s)
Debug: 1.1.2 : (Gen ?Goal)
Debug: 1.1.2: looking for (Gen ?Goal) with backtracking
Debug: 1.1.2.1: simple apply @genOption on (Gen ?Goal), 1 subgoal(s)
Debug: 1.1.2.1.2 : (Gen ?Goal)
Debug: 1.1.2.1.2: looking for (Gen ?Goal) with backtracking
Debug: 1.1.2.1.2.1: simple apply @genOption on (Gen ?Goal), 1 subgoal(s)
Debug: 1.1.2.1.2.1.2 : (Gen ?Goal)
Debug: 1.1.2.1.2.1.2: looking for (Gen ?Goal) with backtracking
```
In practice, ill-typed programs usually fall into infinite loops, but `arbitrary` is obviously well-typed.
I haven't got an immediate solution to it, but you can interrupt the prover with `C-c C-c`.

**Comment by Lysxia** [comment]
Thank you for the pointers.

`genList` and `genOptions` seem to be the culprits here. That's why there is no problem when we just import `QuickChick.Classes`, which has no instances for concrete types.

Resolution terminates if we set a higher priority number than the default...

```
Instance genList {A : Type} `{Gen A} : Gen (list A) | 5 :=  ...
Instance genOption {A} `{Gen A} : Gen (option A) | 5 := ...
```

But with a somewhat unexpected instance:

```
arbitrary
     : GenLow.GenLow.G BinNums.Z
```
