### ISSUE TITLE
Put opam package in coq/released

### ISSUE THREAD

**Issue by mattam82** [QuickChick/QuickChick#52]
Hi, I'm wondering why you didn't put the opam package in the coq opam archive yet? I guess there's not much to do here since you already have an opam file. Note that we also have an extra-dev repository for development versions if things are not quite ready for prime-time yet.

https://coq.inria.fr/packages
https://coq.inria.fr/opam/www/packaging.html

**Comment by zoep** [comment]
Hi Matthieu, 

I think the plan was to put it in opam after we port QuickChick to 8.7 but then few things broke and we haven't fixed that yet.  I guess the version that works with 8.6 is stable enough for the dev repository so we might as well put it there.

**Comment by mattam82** [comment]
Indeed, that’d be good, 8.6 is a perfectly fine target many people use! BTW
you might consider adding QuickChick to the Coq CI suite when you catch up
to 8.7 and then master so that you can get informed when changes in Coq
break it (and most of the time free patches from Coq devs to integrate
fixes).
— Matthieu

**Comment by liyishuai** [comment]
I observe two issues about releasing via OPAM:
1. The name of [Coq packages](https://coq.inria.fr/opam/www/) begin with `coq-`. Maybe we should rename the package to `coq-quickchick`?
2. We should start [semantic versioning](https://semver.org/).

**Comment by liyishuai** [comment]
In progress: coq/opam-coq-archive#289
