### ISSUE TITLE
Solve issues with forAllShrink and promote

### ISSUE THREAD

**Issue by catalin-hritcu** [QuickChick/QuickChick#7]
Promote has a bit of a funny semantics:(https://github.com/QuickChick/QuickChick/blob/master/src/SetOfOutcomes.v#L50
so Zoe didn't include it in her thesis. We should see if that's fixable.

**Comment by zoep** [comment]
Currently, we have a (very concrete) spec about promote which along two (very concrete) specs about bind and fmap make the fact we wanted to prove about shrinking provable. We have different kind of issues with forAllShrink though, see issue ??.

**Comment by catalin-hritcu** [comment]
So can this be closed?

**Comment by zoep** [comment]
The spec we have for promote is pretty trivial (pretty much its definition), but from this we can prove what we want for shrinking, so I think are fine.

**Comment by catalin-hritcu** [comment]
Cool, closing.
