### ISSUE TITLE
What does the frequency in `backtrack` mean?

### ISSUE THREAD

**Issue by liyishuai** [QuickChick/QuickChick#70]
I'm confused about how to describe the meaning of frequency field. If we define the following generator:
```
Definition x : G (option nat) := elems [Some 1; Some 2; None].
Definition y : G (option nat) := elems [Some 3; None].
Definition z : G (option nat) := backtrack [(3,x);(2,y)].
```
The ratio of `z` generating `None` : `Some 1` : `Some 2` : `Some 3` is 5:8:8:9, which seems nonintuitive.

**Comment by Lysxia** [comment]
The semantics of `z` is:

1. pick `x` or `y` with probabilities according to the weights
2. try to generate a value with the picked generator
3.    1. If it is `Some thing` then that's the output of `z`
       2. If it is `None`, then remove the generator and its weight from the list, and restart from step 1 with the new list of generators (which will only have one choice left here)
4. Generators in the list are only run at most once, and they may all generate `None`, in which case the output of `z` is `None` again.

---

For the probability of picking `None`, there are two disjoint possibilities:

1.    1. pick `x` (P=3/5)
      2. pick `None` in `x` (P=1/3)
      3. backtrack
      4. pick `y` (P=3/3, we removed `x` when we picked it)
      5. pick `None` in `y` (P=1/2);
2.    1. pick `y` (P=2/5)
      2. pick `None` in `y` (P=1/2)
      3. backtrack
      4. pick `y` (P=2/2)
      5. pick `None` in `x` (P=1/3).

This adds up to

> (3/5 × 1/3 × 1/2) + (2/5 × 1/2 × 1/3)
> = 1/6
> = 5/(5 + 8 + 8 + 9).

---

For the probability of picking `Some 1`:

1.    1. pick `x` (P=3/5)
      2. pick `Some 1` in `x`(P=1/3);
2.    1. pick `y` (P=2/5)
      2. pick `None` in `y` (P=1/2)
      3. backtrack
      4. pick `x` (P=3/3)
      5. pick `Some 1` in `x` (P=1/3).

> (3/5 × 1/3) + (2/5 × 1/2 × 1/3)
> = 4/15
> = 8/(5 + 8 + 8 + 9)

**Comment by liyishuai** [comment]
By defining `z`, I (and probably other users) expect that 3/5 of the results come from `x` and 2/5 of the results come from `y`, and as a consequence, `Some 1` and `Some 3` have the same ratio.
This can be implemented by decreasing the generator's weight by 1 instead of removing it entirely. One concern of doing so is that the worst case complexity becomes linear to the weights.

**Comment by liyishuai** [comment]
The distribution I proposed in previous comment doesn't seem achievable.
