### ISSUE TITLE
Formally justifying our sets of values abstraction: porting guarantees to concrete instantiation

### ISSUE THREAD

**Issue by catalin-hritcu** [QuickChick/QuickChick#8]
Once we proved a specification for the set of outcomes semantics of a generator, what exactly can we deduce about the concrete semantics?

**Comment by zoep** [comment]
In the "axiom-free" version we have that 

     forall A (g : G A) (x : A),
         semGen g x <-> exists size seed, run g seed size = x.

which I guess is pretty much the connection we need about the set of outcomes and the concrete semantics.

**Comment by catalin-hritcu** [comment]
This seems good enough for me. Closing this.
