### ISSUE TITLE
8.8 branch no longer builds with Coq 8.8

### ISSUE THREAD

**Issue by Lysxia** [QuickChick/QuickChick#83]
`master` got merged into `8.8`, including #80 which is not compatible with `coq.8.8`. CI is not catching this because Travis is using `coq.dev` on this branch now.

https://github.com/QuickChick/QuickChick/blob/0d48f83bed6750f85d1b9564a430ad3af6e9bb48/.travis.yml#L46

**Comment by Lysxia** [comment]
I'm not sure how much of the CI updates to revert.

**Comment by liyishuai** [comment]
We could force revert 0d48f83bed6750f85d1b9564a430ad3af6e9bb48 for convenient 8.8 -> master merges in the future.
The question is whether we want to base future development on master or 8.8.

**Comment by Lysxia** [comment]
I don't have `coq.dev` installed locally, and I wouldn't expect users or contributors to have it either, so my vote goes to 8.8 as the development branch (and we might want to make it the default branch on Github).

**Comment by Lysxia** [comment]
Oh, the releases of QuickChick are tied to those of Coq?

**Comment by Lysxia** [comment]
This seems to have been fixed!
