### ISSUE TITLE
Make a toplevel QuickChick module

### ISSUE THREAD

**Issue by Lysxia** [QuickChick/QuickChick#89]
I want to be able to do

    Require Import QuickChick.

not have to

     Require Import QuickChick.QuickChick.

**Comment by Lysxia** [comment]
Is there no way to avoid the repetition? QuickChick really fits in one module (it works quite well for QuickCheck).

**Comment by liyishuai** [comment]
With Haskell we need `import Test.QuickCheck`. Consider changing the first `QuickChick` to `Test`?

**Comment by Lysxia** [comment]
I don't think the qualification buys us much.

**Comment by Lysxia** [comment]
For now achieving this seems more trouble than it's worth.
