### ISSUE TITLE
Add strong abstraction barriers

### ISSUE THREAD

**Issue by catalin-hritcu** [QuickChick/QuickChick#9]
The way we write generators is very principled, but this is currently just convention and it is not enforced by strong abstraction barriers. For instance the MkGen constructor should really only be available to the concrete implementation of the primitive generators, but not to derived ones. Also the combinators in higher layers in the cake should depend only on the existence and specification of the combinators in the lower layers.

Strong abstraction might also be the key for using parametricity in #8.

I remember discussing about this with Zoe in the past, will need to look at the notes and try to summarize that.

**Comment by zoep** [comment]
I think that this is accomplished in the newest version (semGen branch) with two modules. The first module (Gen) includes the definition of Gen type, primitive combinators as well as proofs about them. The second module includes non-primitive combinators and proofs about them. This way the definitions are only locally accessible and proofs in higher layers only depend on proofs from lower layers and not definitions.

**Comment by catalin-hritcu** [comment]
Indeed, closing this.

**Comment by zoep** [comment]
Just a note on this: We might want to consider closing the checkers and their proofs in a module, just like generators, that would prevent the "user" from unfolding their definitions during a proof.
